services:
  postgres:
    image: postgres:16
    container_name: gymrpg-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: gymrpg
      POSTGRES_PASSWORD: gymrpg123
      POSTGRES_DB: gymrpg_db
    ports:
      - "5432:5432"
    volumes:
      - gymrpg_pg_data:/var/lib/postgresql/data

volumes:
  gymrpg_pg_data: